(function(g){var window=this;var $xa=function(a,b){return g.Ub(a,b)},I6=function(a){g.Bm(a,"zx",g.Ab());
return a},J6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.Em(a.g,b,c)},aya=function(a,b){var c=[];
g.kk(b,function(a){try{var b=g.XC.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.WC(b)&&c.push(a):c.push(a)},a);
return c},bya=function(a,b){var c=aya(a,b);
(0,g.C)(c,function(a){g.XC.prototype.remove.call(this,a)},a)},cya=function(){var a=g.rG;
bya(a,a.g.Yd(!0))},dya=function(a,b,c,d){var e=new g.sm(null,void 0);
a&&g.tm(e,a);b&&g.um(e,b);c&&g.vm(e,c);d&&g.wm(e,d);return e},eya=function(a){g.FF[a]&&(a=g.FF[a],(0,g.C)(a,function(a){g.DF[a]&&delete g.DF[a]}),a.length=0)},fya=function(a){var b=g.CF();
if(b)if(b.clear(a),a)eya(a);else for(var c in g.FF)eya(c)},K6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.mm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",gya(this,a.capabilities||""),hya(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},gya=function(a,b){a.capabilities.clear();
(0,g.Hd)(b.split(","),g.Da($xa,iya)).forEach(function(b){a.capabilities.add(b)})},hya=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},L6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},M6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},jya=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kya=function(a){return new L6(a)},lya=function(a){return g.xa(a)?(0,g.H)(a,kya):[]},N6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},O6=function(a){return g.xa(a)?"["+(0,g.H)(a,N6).join(",")+"]":"null"},P6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},mya=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},Q6=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},R6=function(a,b){return g.Ja(a,function(a){return M6(a,b)})},S6=function(){var a=g.uG("yt-remote-connected-devices")||[];
g.gb(a);return a},nya=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},oya=function(a){g.tG("yt-remote-connected-devices",a,86400)},U6=function(){if(T6)return T6;
var a=g.uG("yt-remote-device-id");a||(a=P6(),g.tG("yt-remote-device-id",a,31536E3));for(var b=S6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return T6=d},V6=function(){var a=S6(),b=U6();
g.Pa(a,b);g.zG()&&g.jb(a,b);a=nya(a);if(g.Qa(a))try{g.xG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.yG("remote_sid",a.join(","),-1)}catch(c){}},pya=function(){return g.uG("yt-remote-session-browser-channel")},qya=function(){return g.uG("yt-remote-local-screens")||[]},rya=function(){g.tG("yt-remote-lounge-token-expiration",!0,86400)},sya=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(qya(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.am)(c,function(a){return!g.Pa(b,a)})&&rya();
g.tG("yt-remote-local-screens",a,31536E3)},tya=function(a,b){g.tG("yt-remote-session-browser-channel",a);
g.tG("yt-remote-session-screen-id",b);var c=S6(),d=U6();g.Pa(c,d)||c.push(d);oya(c);V6()},W6=function(a){a||(g.vG("yt-remote-session-screen-id"),g.vG("yt-remote-session-video-id"));
V6();a=S6();g.Ua(a,U6());oya(a)},uya=function(){if(!X6){var a=g.cD();
a&&(X6=new g.RC(a))}return X6?!!X6.get("yt-remote-use-staging-server"):!1},vya=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Eb(a)},wya=function(a,b){var c=g.zd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Xc(c,g.Zd("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},xya=function(){var a=vya(),b=window.document.getElementById(a),c=b&&g.QE(b,"loaded");
c||b&&!c||(b=wya(a,function(){g.QE(b,"loaded")||(g.PE(b,"loaded","true"),g.JF(a),g.LD(g.Da(fya,a),0))}))},Y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},yya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Z6=function(a){a.length?zya(a.shift(),function(){Z6(a)}):$6()},Aya=function(a){return"chrome-extension://"+a+a7},zya=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},b7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},$6=function(){var a=yya();
a&&a(!1,"No cast extension found")},c7=function(){if(Bya){var a=2,b=yya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;zya("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",$6,c)}},Cya=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(c7(),a({command:"cast.sender.init"}))},Dya=function(){c7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+a7,"//www.gstatic.com/eureka/clank"+a7])},d7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.sc=b;this.B=(0,g.z)(this.NH,this);this.g=!1;this.l=0;this.o=this.za=null;this.A=[]},e7=function(){},f7=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Im(this);this.l=new g.ng;this.l.setInterval(250)},Fya=function(a,b,c){a.lj=1;
a.jh=I6(b.clone());a.Fi=c;a.C=!0;Eya(a,null)},g7=function(a,b,c,d,e){a.lj=1;
a.jh=I6(b.clone());a.Fi=null;a.C=c;e&&(a.gC=!1);Eya(a,d)},Eya=function(a,b){a.Pj=(0,g.F)();
h7(a);a.Ch=a.jh.clone();J6(a.Ch,"t",a.D);a.Pl=0;a.Lc=a.g.tq(a.g.Jl()?b:null);0<a.Yq&&(a.Ho=new g.Qk((0,g.z)(a.tD,a,a.Lc),a.Yq));a.A.P(a.Lc,"readystatechange",a.KS);var c=a.fi?g.bc(a.fi):{};a.Fi?(a.qp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Lc.send(a.Ch,a.qp,a.Fi,c)):(a.qp="GET",a.gC&&!g.vd&&(c.Connection="close"),a.Lc.send(a.Ch,a.qp,null,c));a.g.qf(1)},Iya=function(a,b,c){for(var d=!0;!a.Ph&&a.Pl<c.length;){var e=Gya(a,c);
if(e==i7){4==b&&(a.kh=4,j7(15),d=!1);break}else if(e==Hya){a.kh=4;j7(16);d=!1;break}else k7(a,e)}4==b&&0==c.length&&(a.kh=1,j7(17),d=!1);a.uf=a.uf&&d;d||(l7(a),m7(a))},Gya=function(a,b){var c=a.Pl,d=b.indexOf("\n",c);
if(-1==d)return i7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return Hya;d+=1;if(d+c>b.length)return i7;var e=b.substr(d,c);a.Pl=d+c;return e},Kya=function(a,b){a.Pj=(0,g.F)();
h7(a);var c=b?window.location.hostname:"";a.Ch=a.jh.clone();g.Bm(a.Ch,"DOMAIN",c);g.Bm(a.Ch,"t",a.D);try{a.vf=new window.ActiveXObject("htmlfile")}catch(n){l7(a);a.kh=7;j7(22);m7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in n7)k=n7[l];else if(l in Jya)k=n7[l]=Jya[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=n7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Yc(g.vc("b/12014412"),d);a.vf.open();a.vf.write(g.Qc(c));a.vf.close();a.vf.parentWindow.m=(0,g.z)(a.PR,a);a.vf.parentWindow.d=(0,g.z)(a.xB,a,!0);a.vf.parentWindow.rpcClose=(0,g.z)(a.xB,a,!1);c=a.vf.createElement("DIV");a.vf.parentWindow.document.body.appendChild(c);d=g.Hc(a.Ch.toString());d=g.qb(g.Ec(d));d=g.Yc(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Qc(d);
a.g.qf(1)},h7=function(a){a.Gu=(0,g.F)()+a.B;
Lya(a,a.B)},Lya=function(a,b){if(null!=a.kk)throw Error("WatchDog timer not null");
a.kk=o7((0,g.z)(a.gS,a),b)},p7=function(a){a.kk&&(g.w.clearTimeout(a.kk),a.kk=null)},m7=function(a){a.g.Gx()||a.Ph||a.g.xo(a)},l7=function(a){p7(a);
g.We(a.Ho);a.Ho=null;a.l.stop();g.Om(a.A);if(a.Lc){var b=a.Lc;a.Lc=null;b.abort();b.dispose()}a.vf&&(a.vf=null)},k7=function(a,b){try{a.g.qB(a,b),a.g.qf(4)}catch(c){}},Nya=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Mya(a,b,function(e){e?c(!0):g.w.setTimeout(function(){Nya(a,b,c,d,f)},f)})}},Mya=function(a,b,c){var d=new window.Image;
d.onload=function(){try{q7(d),c(!0)}catch(e){}};
d.onerror=function(){try{q7(d),c(!1)}catch(e){}};
d.onabort=function(){try{q7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{q7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},q7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Oya=function(a){this.g=a;
this.l=new e7},Pya=function(a){var b=r7(a.g,a.qk,"/mail/images/cleardot.gif");
I6(b);Nya(b.toString(),5E3,(0,g.z)(a.YG,a),3,2E3);a.qf(1)},t7=function(a){var b=a.g.H;
if(null!=b)j7(5),b?(j7(11),s7(a.g,a,!1)):(j7(12),s7(a.g,a,!0));else if(a.pe=new f7(a,void 0,void 0,void 0),a.pe.fi=a.Vq,b=a.g,b=r7(b,b.Jl()?a.Pk:null,a.Xq),j7(5),!g.td||g.rc(10))J6(b,"TYPE","xmlhttp"),g7(a.pe,b,!1,a.Pk,!1);else{J6(b,"TYPE","html");var c=a.pe;a=!!a.Pk;c.lj=3;c.jh=I6(b.clone());Kya(c,a)}},u7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new e7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},Qya=function(a,b){this.g=a;
this.map=b;this.context=null},Rya=function(a){g.Ye.call(this,"statevent",a)},Sya=function(a,b){g.Ye.call(this,"timingevent",a);
this.size=b},Tya=function(a){g.Ye.call(this,"serverreachability",a)},Wya=function(a){Uya(a);
if(3==a.g){var b=a.xl++,c=a.tn.clone();g.Bm(c,"SID",a.o);g.Bm(c,"RID",b);g.Bm(c,"TYPE","terminate");v7(a,c);b=new f7(a,a.o,b,void 0);b.lj=2;b.jh=I6(c.clone());(new window.Image).src=b.jh;b.Pj=(0,g.F)();h7(b)}Vya(a)},Xya=function(a){a.uH(1,0);
a.tn=r7(a,null,a.Uq);w7(a)},Uya=function(a){a.Yg&&(a.Yg.abort(),a.Yg=null);
a.oc&&(a.oc.cancel(),a.oc=null);a.rg&&(g.w.clearTimeout(a.rg),a.rg=null);x7(a);a.Nd&&(a.Nd.cancel(),a.Nd=null);a.ah&&(g.w.clearTimeout(a.ah),a.ah=null)},Yya=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new Qya(a.KN++,b));2!=a.g&&3!=a.g||w7(a)},w7=function(a){a.Nd||a.ah||(a.ah=o7((0,g.z)(a.vB,a),0),a.dj=0)},$ya=function(a,b){if(1==a.g){if(!b){a.xl=Math.floor(1E5*Math.random());
var c=a.xl++,d=new f7(a,"",c,void 0);d.fi=null;var e=y7(a),f=a.tn.clone();g.Bm(f,"RID",c);g.Bm(f,"CVER","1");v7(a,f);Fya(d,f,e);a.Nd=d;a.g=2}}else 3==a.g&&(b?Zya(a,b):0==a.l.length||a.Nd||Zya(a))},Zya=function(a,b){if(b)if(6<a.Rh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.xl-1;var d=y7(a)}else c=b.F,d=b.Fi;else c=a.xl++,d=y7(a);var e=a.tn.clone();g.Bm(e,"SID",a.o);g.Bm(e,"RID",c);g.Bm(e,"AID",a.yj);v7(a,e);c=new f7(a,a.o,c,a.dj+1);c.fi=null;c.setTimeout(Math.round(1E4)+Math.round(1E4*Math.random()));a.Nd=c;Fya(c,e,d)},v7=function(a,b){if(a.nd){var c=a.nd.kx();
c&&g.Lb(c,function(a,c){g.Bm(b,c,a)})}},y7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Rh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Rh?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},aza=function(a){a.oc||a.rg||(a.D=1,a.rg=o7((0,g.z)(a.uB,a),0),a.Ui=0)},z7=function(a){if(a.oc||a.rg||3<=a.Ui)return!1;
a.D++;a.rg=o7((0,g.z)(a.uB,a),bza(a,a.Ui));a.Ui++;return!0},s7=function(a,b,c){a.pp=c;
a.df=b.yg;a.C||Xya(a)},x7=function(a){null!=a.Th&&(g.w.clearTimeout(a.Th),a.Th=null)},bza=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},A7=function(a,b){if(2==b||9==b){var c=null;
a.nd&&(c=null);var d=(0,g.z)(a.HT,a);c||(c=new g.sm("//www.google.com/images/cleardot.gif"),I6(c));Mya(c.toString(),1E4,d)}else j7(2);cza(a,b)},cza=function(a,b){a.g=0;
a.nd&&a.nd.hw(b);Vya(a);Uya(a)},Vya=function(a){a.g=0;
a.df=-1;if(a.nd)if(0==a.A.length&&0==a.l.length)a.nd.hq();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.nd.hq(b)}},r7=function(a,b,c){var d=g.Cm(c);
if(""!=d.l)b&&g.um(d,b+"."+d.l),g.vm(d,d.B);else{var e=window.location;d=dya(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Ck&&g.Lb(a.Ck,function(a,b){g.Bm(d,b,a)});
g.Bm(d,"VER",a.Rh);v7(a,d);return d},o7=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},j7=function(a){B7.dispatchEvent(new Rya(B7,a))},dza=function(){},eza=function(a,b){this.action=a;
this.params=b||{}},D7=function(a,b){g.M.call(this);
this.g=new g.Vt(this.o,0,this);g.N(this,this.g);this.l=this.sc=0;if(g.za(a))b&&(a=(0,g.z)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a;C7(this)},C7=function(a){a.g.stop();
a.sc=5E3+2E4*Math.random()},E7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.QC;this.l=new D7(this.sU,this);this.g=this.bb=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.L=c||!1},fza=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.pp,sessionId:a.g.o,arrayId:a.g.yj}},gza=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&$ya(a.g),Wya(a.g));a.F=0},F7=function(a){return!!a.g&&3==a.g.g},hza=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},G7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Dg(a)||"";b&&(this.port=":"+b);this.domain=g.Cg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Db(a,"10.0")&&(this.l=!1))},H7=function(a,b){var c=a.g;
if(g.u(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Mg(c+b,{})},I7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Jb:g.Da(a.A,d,!0),onError:g.Da(a.o,e),rd:g.Da(a.B,e)};c&&(a.Mb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.aE(b,a)},lza=function(){var a=iza;
jza();J7.push(a);kza(J7)},K7=function(a,b){jza();
var c=J7,d=mza(a,String(b));g.Qa(c)?nza(d):(kza(c),(0,g.C)(c,function(a){a(d)}))},jza=function(){J7||(J7=g.x("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",J7,void 0))},nza=function(a){var b=(L7+1)%50;
L7=b;M7[b]=a;N7||(N7=49==b)},kza=function(a){var b=M7;
if(b[0]){var c=L7,d=N7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
M7=Array(50);L7=-1;N7=!1}},mza=function(a,b){var c=((0,g.F)()-oza)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},O7=function(a){g.uF.call(this);
this.D=a;this.g=[]},pza=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},qza=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Hd)(a.g,function(a){return!!Q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=pza(a,b[d])||c;return c},rza=function(a,b){var c=a.g.length;
a.g=(0,g.Hd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},P7=function(a,b,c,d){g.uF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.za=window.NaN},R7=function(a){O7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;Q7(this);this.info("Initializing with "+O6(this.g))},sza=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=H7(a.o,"/pairing/get_lounge_token_batch");
I7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.ZH,a),(0,g.z)(a.YH,a))}},Q7=function(a){var b=lya(qya());
b=(0,g.Hd)(b,function(a){return!a.uuid});
return qza(a,b)},S7=function(a,b){sya((0,g.H)(a.g,jya));
b&&rya()},U7=function(a,b){g.uF.call(this);
this.C=b;var c=g.uG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;T7("Initialized with "+g.ug(this.g))},tza=function(a,b,c){var d=H7(a.B,"/pairing/get_screen_availability");
I7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},V7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(T7("Updated online screens: "+g.ug(a.g)),a.g=b,a.R("screenChange"));uza(a)},W7=function(a){(0,window.isNaN)(a.o)||g.ND(a.o);
a.o=g.LD((0,g.z)(a.Qt,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},T7=function(a){K7("OnlineScreenService",a)},vza=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.ac("Requesting availability of screen w/o lounge token.")});
return b},uza=function(a){a=g.Rb(g.Mb(a.g,function(a){return a}));
g.gb(a);a.length?g.tG("yt-remote-online-screen-ids",a.join(","),60):g.vG("yt-remote-online-screen-ids")},X7=function(a){O7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};wza(this)},yza=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.he();if(k=(c?R6(k,c):null)||R6(k,b)){k.uuid=b;var l=Y7(a,k);tza(a.l,l,function(a){e(a?l:null)})}else c?xza(a,c,(0,g.z)(function(a){var f=Y7(this,new L6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));tza(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},zza=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},xza=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Mb:{screen_ids:b},method:"POST",context:a,Jb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.aE(H7(a.C,"/pairing/get_lounge_token_batch"),e)},Aza=function(a){a.g=a.o.he();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+O6(a.g))},wza=function(a){Z7(a);
a.o=new R7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.pI,a));Aza(a);a.A=lya(g.uG("yt-remote-automatic-screen-cache")||[]);Z7(a);a.info("Initializing automatic screens: "+O6(a.A));a.l=new U7(a.C,(0,g.z)(a.he,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},Y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=R6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.tG("yt-remote-automatic-screen-cache",(0,g.H)(a.A,jya)));Z7(a);a.B[b.uuid]=b.id;g.tG("yt-remote-device-id-map",a.B,31536E3);return b},Z7=function(a){a.B=g.uG("yt-remote-device-id-map")||{}},$7=function(a,b,c){g.uF.call(this);
this.L=c;this.H=a;this.l=b;this.o=null},a8=function(a,b){K7(a.L,b)},b8=function(a,b){$7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.yU,this);this.B=(0,g.z)(this.qS,this);this.A=g.LD((0,g.z)(function(){Bza(this,null)},this),12E4)},Cza=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.ug(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){a8(this,"Failed to send message: getMdxSessionStatus.")},a)):a8(a,"Sending yt message without session: "+g.ug(b))},Bza=function(a,b){g.ND(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.yo,a),d=(0,g.z)(a.ne,a);a.zx(b,c,d,5)}}else a.ne(Error("Waiting for session status timed out."))},c8=function(a,b,c){$7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.BU,this);this.g=g.y},Dza=function(a){a.g=a.H.zD(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.yo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.ne(a)},a))},Eza=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}uya()&&(b.env_useStageMdx=1);return g.Kg(b)},d8=function(a,b){$7.call(this,a,b,"ManualSession");
this.g=g.LD((0,g.z)(this.zj,this,null),150)},e8=function(a,b,c,d){g.uF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.WQ,this)},Fza=function(a,b){return b?g.Ja(a.o,function(a){return M6(b,a.label)},a):null},f8=function(a){K7("Controller",a)},iza=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},g8=function(a){return a.B||!!a.o.length||!!a.g},h8=function(a,b,c){b!=a.g&&(g.We(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.sB,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.zj(null)):a.R("yt-remote-cast2-session-change",null))},Gza=function(a){var b=a.l.yD(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&M6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=Fza(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Mza=function(a,b,c,d,e,f,k){Hza()?Iza(b,e,f,k)&&(j8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Jza(a,c):(window.__onGCastApiAvailable=function(b,d){b?Jza(a,c):(k8("Failed to load cast API: "+d),l8(!1),j8(!1),g.vG("yt-remote-cast-available"),g.vG("yt-remote-cast-receiver"),Kza(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):xya():b7("CriOS")?Cya():b7("Android")&&b7("Chrome/")&&window.navigator.presentation?Dya():window.chrome&&window.navigator.presentation&&!b7("Edge")?(c7(),Z6(Lza.map(Aya))):$6())):i8("Cannot initialize because not running Chrome")},Kza=function(){i8("dispose");
var a=m8();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);Nza(!1);g.HF(n8);n8.length=0},o8=function(){return!!g.uG("yt-remote-cast-installed")},Oza=function(){var a=g.uG("yt-remote-cast-receiver");
return a?a.friendlyName:null},Pza=function(){i8("clearCurrentReceiver");
g.vG("yt-remote-cast-receiver")},Qza=function(){return o8()?m8()?m8().getCastSession():(k8("getCastSelector: Cast is not initialized."),null):(k8("getCastSelector: Cast API is not installed!"),null)},q8=function(){o8()?m8()?p8()?(i8("Requesting cast selector."),m8().requestSession()):(i8("Wait for cast API to be ready to request the session."),n8.push(g.GF("yt-remote-cast2-api-ready",q8))):k8("requestCastSelector: Cast is not initialized."):k8("requestCastSelector: Cast API is not installed!")},r8=
function(a,b){p8()?m8().setConnectedScreenStatus(a,b):k8("setConnectedScreenStatus called before ready.")},Hza=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.jJ||a},Rza=function(a,b){m8().init(a,b)},Iza=function(a,b,c,d){var e=!1;
m8()||(a=new e8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.tG("yt-remote-cast-available",a);g.KF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){i8("onReceiverSelected: "+a.friendlyName);
g.tG("yt-remote-cast-receiver",a);g.KF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){i8("onReceiverResumed: "+a.friendlyName);
g.tG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){i8("onSessionChange: "+N6(a));
a||g.vG("yt-remote-cast-receiver");g.KF("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
i8("cloudview.createSingleton_: "+e);return e},m8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Jza=function(a,b){l8(!0);
j8(!1);Rza(a,function(a){a?(Nza(!0),g.JF("yt-remote-cast2-api-ready")):(k8("Failed to initialize cast API."),l8(!1),g.vG("yt-remote-cast-available"),g.vG("yt-remote-cast-receiver"),Kza());b(a)})},i8=function(a){K7("cloudview",a)},k8=function(a){K7("cloudview",a)},l8=function(a){i8("setCastInstalled_ "+a);
g.tG("yt-remote-cast-installed",a)},p8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Nza=function(a){i8("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},j8=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},s8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Jf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},t8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Jf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},u8=function(a){return a.jb()?((0,g.F)()-a.D)/1E3:0},v8=function(a,b){a.F=b;
a.D=(0,g.F)()},w8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},x8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&t8(a)},y8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.l);b.hasPrevious=a.Jf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},A8=function(a,b){g.uF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.gC;this.o=this.l=null;this.H=(0,g.z)(this.uO,this);this.D=(0,g.z)(this.zl,this);this.F=(0,g.z)(this.tO,this);this.I=(0,g.z)(this.HO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Nu,this),Sza(this))):c=3;0!=c&&(b?this.Nu(c):g.LD((0,g.z)(function(){this.Nu(c)},this),0));
var d=Qza();d&&z8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},B8=function(a){return new s8(a.A.getPlayerContextData())},Sza=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Da(this.SQ,a),this))},a)},Tza=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},C8=function(a,b){50>a.B.Hc()&&g.iC(a.B,b)},E8=function(a,b,c){var d=B8(a);
v8(d,c);-1E3!=d.g&&(d.g=b);D8(a,d)},F8=function(a,b,c){a.A.sendMessage(b,c)},D8=function(a,b){Tza(a);
a.A.setPlayerContextData(y8(b));Sza(a)},z8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.zl(null));
a.o=b;a.o&&(K7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.zl(a.o.media[0]))},Uza=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=B8(a);b.contentId!=d.videoId&&K7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;v8(d,a.l.getEstimatedTime());D8(a,d)}else K7("CP","No cast media video. Ignoring state update.")},G8=function(a,b,c){return(0,g.z)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),F8(this,b,c))},a)},H8=function(a,b,c){g.uF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.L=window.NaN;this.V=[];this.A=this.D=this.o=this.fb=this.g=null;this.na=a;this.V.push(g.eF(window,"beforeunload",(0,g.z)(this.QH,this)));this.l=[];this.fb=new s8;this.X=b.id;this.g=Vza(this,c);this.g.subscribe("handlerOpened",this.yO,this);this.g.subscribe("handlerClosed",this.vO,this);this.g.subscribe("handlerError",this.wO,this);this.g.subscribe("handlerMessage",this.xO,this);hza(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.fb.videoId;g.zG()&&g.tG("yt-remote-session-video-id",a)},this)},I8=function(a){K7("conn",a)},Vza=function(a,b){return new E7(H7(a.na,"/bc"),b)},J8=function(a,b){a.R("proxyStateChange",b)},Wza=function(a){a.B=g.LD((0,g.z)(function(){I8("Connecting timeout");
this.C(1)},a),2E4)},K8=function(a){g.ND(a.B);
a.B=window.NaN},L8=function(a){g.ND(a.L);
a.L=window.NaN},Xza=function(a){M8(a);
a.K=g.LD((0,g.z)(function(){N8(this,"getNowPlaying")},a),2E4)},M8=function(a){g.ND(a.K);
a.K=window.NaN},Zza=function(a,b){b&&(K8(a),L8(a));
b==(F7(a.g)&&(0,window.isNaN)(a.B))?b&&(J8(a,1),N8(a,"getSubtitlesTrack")):b?(a.W()&&a.fb.reset(),J8(a,1),N8(a,"getNowPlaying"),Yza(a)):a.C(1)},$za=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.fb.videoId&&(g.Xb(b.params)?a.fb.l=null:a.fb.l=b.params,a.R("remotePlayerChange"))},aAa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.fb.listId=b.params.listId||a.fb.listId;x8(a.fb,c,d);a.R("remoteQueueChange")},cAa=function(a,b){b.params=b.params||{};
aAa(a,b);bAa(a,b);a.R("autoplayDismissed")},bAa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
v8(a.fb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.fb.g&&(c=-1E3);a.fb.g=c;c=Number(b.params.loadedTime);a.fb.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.fb.H=(0,window.isNaN)(c)?0:c;c=a.fb;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.fb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.fb.g?Xza(a):M8(a);
a.R("remotePlayerChange")},dAa=function(a,b){if(-1E3!=a.fb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.fb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);v8(a.fb,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},eAa=function(a,b){var c="true"==b.params.muted;
a.fb.volume=(0,window.parseInt)(b.params.volume,10);a.fb.muted=c;a.R("remotePlayerChange")},fAa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},gAa=function(a,b){var c="true"==b.params.hasNext;
a.fb.Jf="true"==b.params.hasPrevious;a.fb.hasNext=c;a.R("previousNextChange")},Yza=function(a){g.ND(a.I);
a.I=g.LD((0,g.z)(a.C,a,1),864E5)},N8=function(a,b,c){c?I8("Sending: action="+b+", params="+g.ug(c)):I8("Sending: action="+b);
a.g.sendMessage(b,c)},O8=function(a){O7.call(this,"ScreenServiceProxy");
this.bd=a;this.l=[];this.l.push(this.bd.$_s("screenChange",(0,g.z)(this.wU,this)));this.l.push(this.bd.$_s("onlineScreenChange",(0,g.z)(this.tQ,this)))},lAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.FD("MDX_CONFIG")||b;g.rG&&cya();V6();P8||(P8=new G7(b?b.loungeApiHost:void 0),uya()&&(P8.g="/api/loungedev"));Q8||(Q8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",Q8,void 0));hAa();var c=R8();if(!c){var d=new X7(P8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=R8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Mza(a,d,function(a){a?S8()&&r8(S8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.KF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),T8("Initializing: "+g.ug(b)),U8.push(g.GF("yt-remote-cast2-availability-change",function(){g.KF("yt-remote-receiver-availability-change")})),U8.push(g.GF("yt-remote-cast2-receiver-selected",function(){V8(null);
g.KF("yt-remote-auto-connect","cast-selector-receiver")})),U8.push(g.GF("yt-remote-cast2-receiver-resumed",function(){g.KF("yt-remote-receiver-resumed","cast-selector-receiver")})),U8.push(g.GF("yt-remote-cast2-session-change",iAa)),U8.push(g.GF("yt-remote-connection-change",function(a){a?r8(S8(),"YouTube TV"):W8()||(r8(null,null),Pza())})),a=X8(),b.isAuto&&(a.id+="#dial"),g.vE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),T8(" -- with channel params: "+
g.ug(a)),jAa(a),c.start(),S8()||kAa())},nAa=function(){var a=mAa();
o8()&&g.uG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},mAa=function(){var a=R8().bd.$_gos();
var b=Y8();b&&Z8()&&(Q6(a,b)||a.push(b));return mya(a)},$8=function(){var a=oAa();
!a&&o8()&&Oza()&&(a={key:"cast-selector-receiver",name:Oza()});return a},oAa=function(){var a=mAa(),b=Y8();
b||(b=W8());return g.Ja(a,function(a){return b&&M6(b,a.key)?!0:!1})},Y8=function(){var a=S8();
if(!a)return null;var b=R8().he();return R6(b,a)},iAa=function(a){T8("remote.onCastSessionChange_: "+N6(a));
if(a){var b=Y8();b&&b.id==a.id?r8(b.id,"YouTube TV"):(b&&a9(),b9(a,1))}else Z8()&&a9()},a9=function(){p8()?m8().stopSession():k8("stopSession called before API ready.");
var a=Z8();a&&(a.disconnect(1),c9(null))},d9=function(){var a=Z8();
return!!a&&3!=a.getProxyState()},T8=function(a){K7("remote",a)},R8=function(){if(!e9){var a=g.x("yt.mdx.remote.screenService_");
e9=a?new O8(a):null}return e9},S8=function(){return g.x("yt.mdx.remote.currentScreenId_")},pAa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},qAa=function(){return g.x("yt.mdx.remote.connectData_")},V8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},Z8=function(){return g.x("yt.mdx.remote.connection_")},c9=function(a){var b=Z8();
V8(null);a||pAa("");g.ua("yt.mdx.remote.connection_",a,void 0);Q8&&((0,g.C)(Q8,function(b){b(a)}),Q8.length=0);
b&&!a?g.KF("yt-remote-connection-change",!1):!b&&a&&g.KF("yt-remote-connection-change",!0)},W8=function(){var a=g.zG();
if(!a)return null;var b=R8().he();return R6(b,a)},b9=function(a,b){Y8()&&Y8();
pAa(a.id);var c=new H8(P8,a,X8());c.connect(b,qAa());c.subscribe("beforeDisconnect",function(a){g.KF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){Z8()&&c9(null)});
c9(c)},kAa=function(){var a=W8();
a?(T8("Resume connection to: "+N6(a)),b9(a,0)):(W6(),Pza(),T8("Skipping connecting because no session screen found."))},hAa=function(){var a=X8();
if(g.Xb(a)){a=U6();var b=g.uG("yt-remote-session-name")||"",c=g.uG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},X8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},jAa=function(a){a?(g.tG("yt-remote-session-app",a.app),g.tG("yt-remote-session-name",a.name)):(g.vG("yt-remote-session-app"),g.vG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},f9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.rF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.MP);this.o.O(b,"captionschanged",this.sO);this.o.O(b,"captionssettingschanged",this.KC);this.o.O(b,"videoplayerreset",this.zo);this.o.O(b,"mdxautoplaycancel",this.XG);this.V=this.o.O(b,"onVolumeChange",this.cB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.pB,this);c.subscribe("remotePlayerChange",this.Bl,this);c.subscribe("remoteQueueChange",this.zo,this);c.subscribe("autoplayUpNext",this.LA,
this);c.subscribe("previousNextChange",this.mB,this);c.subscribe("nowAutoplaying",this.eB,this);c.subscribe("autoplayDismissed",this.KA,this);this.suggestion=null;this.H=new g.nO(64);this.A=new g.Vt(this.GC,500,this);g.N(this,this.A);this.B=new g.Vt(this.HC,1E3,this);g.N(this,this.B);this.K=new d7(this.UT,0,this);g.N(this,this.K);this.C={};this.L=new g.Vt(this.nD,1E3,this);g.N(this,this.L);this.I=new g.Qk(this.mL,1E3,this);g.N(this,this.I);this.N=g.y;this.KC();this.zo();this.Bl()},g9=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},rAa=function(a){g9(a,0);
a.A.stop();h9(a,new g.nO(64))},j9=function(a,b){if(i9(a)&&!a.D){var c=null;
b&&(c={style:a.l.xi()},g.ec(c,b));a.g.xC(a.l.ea(1).videoId,c);c=B8(a.g).l;a.C=c}},k9=function(a,b){var c=a.l.Wf();
if(c){var d=c.ee();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.vj;var m=B8(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};x8(m,k,l);g.u(b)&&(v8(m,b),q.currentTime=b);g.u(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);F8(c,"setPlaylist",q);e||D8(c,m);h9(a,new g.nO(1))},sAa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{wy:1});
c&&c.length?(a.l.Fd("captions","track",b),a.D=!1):(a.l.ql("captions"),a.D=!0)}else a.l.Fd("captions","track",{})},i9=function(a){return B8(a.g).videoId==a.l.ea(1).videoId},h9=function(a,b){a.B.stop();
var c=a.H;if(!g.uO(c,b)){var d=g.V(b,2);d!=g.V(a.H,2)&&g.fU(a.l,d);a.H=b;tAa(a.F,c,b)}},l9=function(a){g.Y.call(this,{G:"div",
M:"ytp-remote",J:[{G:"div",M:"ytp-remote-display-status",J:[{G:"div",M:"ytp-remote-display-status-icon",J:[g.cV()]},{G:"div",M:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.zV(this,250);g.N(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);uAa(this,g.cU(a))},uAa=function(a,b){if(3==a.o.Qa()){var c={RECEIVER_NAME:a.o.xc("remote","currentReceiver").name};
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},m9=function(a,b){g.M_.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},n9=function(a){g.DU.call(this,a);
g.BG({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:P6(),name:g.U("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.nO(64);this.H=0;if(!g.WL(g.W(this.g))){a=
this.g;var b=g.VT(a).H;b&&(b=b.o&&b.o.g)&&(b=new m9(a,b),g.N(this,b));b=new l9(a);g.N(this,b);g.xU(a,b.element,4)}},tAa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.AO(c,b))},o9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)a9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Wf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.fc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.vj,index:Math.max(a.g.Iz(),0),currentTime:0==f?void 0:f}}else c=null;T8("Connecting to: "+g.ug(b));"cast-selector-receiver"==b.key?(V8(c||null),p8()?m8().setLaunchParams(c||null):k8("setLaunchParams called before ready.")):!c&&
d9()&&S8()==b.key?g.KF("yt-remote-connection-change",!0):(a9(),V8(c||null),c=R8().he(),(c=R6(c,b.key))&&b9(c,1))}},Jya={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},n7={"'":"\\'"},vAa={},iya={bW:"atp",I0:"ska",W_:"que",g_:"mus",E0:"sus"};
K6.prototype.Zm=function(){var a=new K6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var X6,T6="",a7=Y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Bya=Y6("loadCastFramework")||Y6("loadCastApplicationFramework"),Lza=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(d7,g.M);g.h=d7.prototype;g.h.MH=function(a){this.A=arguments;this.g=!1;this.za?this.o=(0,g.F)()+this.sc:this.za=g.og(this.B,this.sc)};
g.h.stop=function(){this.za&&(g.pg(this.za),this.za=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();d7.Z.U.call(this)};
g.h.NH=function(){this.o?(this.za=g.og(this.B,this.o-(0,g.F)()),this.o=null):(this.za=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};e7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
e7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=f7.prototype;g.h.fi=null;g.h.uf=!1;g.h.kk=null;g.h.Gu=null;g.h.Pj=null;g.h.lj=null;g.h.jh=null;g.h.Ch=null;g.h.Fi=null;g.h.Lc=null;g.h.Pl=0;g.h.vf=null;g.h.qp=null;g.h.kh=null;g.h.Qk=-1;g.h.gC=!0;g.h.Ph=!1;g.h.Yq=0;g.h.Ho=null;var Hya={},i7={};g.h=f7.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.KS=function(a){a=a.target;var b=this.Ho;b&&3==g.nx(a)?b.jj():this.tD(a)};
g.h.tD=function(a){try{if(a==this.Lc)a:{var b=g.nx(this.Lc),c=this.Lc.l,d=this.Lc.getStatus();if(g.td&&!g.rc(10)||g.vd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.$e&&!g.rx(this.Lc))break a;this.Ph||4!=b||7==c||(8==c||0>=d?this.g.qf(3):this.g.qf(2));p7(this);var e=this.Lc.getStatus();this.Qk=e;var f=g.rx(this.Lc);(this.uf=200==e)?(4==b&&l7(this),this.C?(Iya(this,b,f),g.$e&&this.uf&&3==b&&(this.A.P(this.l,"tick",this.DS),this.l.start())):k7(this,f),this.uf&&!this.Ph&&(4==b?this.g.xo(this):
(this.uf=!1,h7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.kh=3,j7(13)):(this.kh=0,j7(14)),l7(this),m7(this))}}catch(k){this.Lc&&g.rx(this.Lc)}finally{}};
g.h.DS=function(){var a=g.nx(this.Lc),b=g.rx(this.Lc);this.Pl<b.length&&(p7(this),Iya(this,a,b),this.uf&&4!=a&&h7(this))};
g.h.PR=function(a){o7((0,g.z)(this.OR,this,a),0)};
g.h.OR=function(a){this.Ph||(p7(this),k7(this,a),h7(this))};
g.h.xB=function(a){o7((0,g.z)(this.NR,this,a),0)};
g.h.NR=function(a){this.Ph||(l7(this),this.uf=a,this.g.xo(this),this.g.qf(4))};
g.h.cancel=function(){this.Ph=!0;l7(this)};
g.h.gS=function(){this.kk=null;var a=(0,g.F)();0<=a-this.Gu?(2!=this.lj&&this.g.qf(3),l7(this),this.kh=2,j7(18),m7(this)):Lya(this,this.Gu-a)};g.h=Oya.prototype;g.h.Vq=null;g.h.pe=null;g.h.Io=!1;g.h.Hx=null;g.h.pn=null;g.h.Wq=null;g.h.Xq=null;g.h.Ke=null;g.h.yg=-1;g.h.Pk=null;g.h.qk=null;g.h.connect=function(a){this.Xq=a;a=r7(this.g,null,this.Xq);j7(3);this.Hx=(0,g.F)();var b=this.g.F;null!=b?(this.Pk=b[0],(this.qk=b[1])?(this.Ke=1,Pya(this)):(this.Ke=2,t7(this))):(J6(a,"MODE","init"),this.pe=new f7(this,void 0,void 0,void 0),this.pe.fi=this.Vq,g7(this.pe,a,!1,null,!0),this.Ke=0)};
g.h.YG=function(a){if(a)this.Ke=2,t7(this);else{j7(4);var b=this.g;b.df=b.Yg.yg;A7(b,9)}a&&this.qf(2)};
g.h.tq=function(a){return this.g.tq(a)};
g.h.abort=function(){this.pe&&(this.pe.cancel(),this.pe=null);this.yg=-1};
g.h.Gx=function(){return!1};
g.h.qB=function(a,b){this.yg=a.Qk;if(0==this.Ke)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.df=this.yg;A7(c,2);return}this.Pk=c[0];this.qk=c[1]}else c=this.g,c.df=this.yg,A7(c,2);else if(2==this.Ke)if(this.Io)j7(7),this.Wq=(0,g.F)();else if("11111"==b){if(j7(6),this.Io=!0,this.pn=(0,g.F)(),c=this.pn-this.Hx,!g.td||g.rc(10)||500>c)this.yg=200,this.pe.cancel(),j7(12),s7(this.g,this,!0)}else j7(8),this.pn=this.Wq=(0,g.F)(),this.Io=!1};
g.h.xo=function(){this.yg=this.pe.Qk;if(this.pe.uf)0==this.Ke?this.qk?(this.Ke=1,Pya(this)):(this.Ke=2,t7(this)):2==this.Ke&&((!g.td||g.rc(10)?!this.Io:200>this.Wq-this.pn)?(j7(11),s7(this.g,this,!1)):(j7(12),s7(this.g,this,!0)));else{0==this.Ke?j7(9):2==this.Ke&&j7(10);var a=this.g;a.df=this.yg;A7(a,2)}};
g.h.Jl=function(){return this.g.Jl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.qf=function(a){this.g.qf(a)};g.h=u7.prototype;g.h.Ck=null;g.h.Nd=null;g.h.oc=null;g.h.Uq=null;g.h.tn=null;g.h.Wv=null;g.h.In=null;g.h.xl=0;g.h.KN=0;g.h.nd=null;g.h.ah=null;g.h.rg=null;g.h.Th=null;g.h.Yg=null;g.h.pp=null;g.h.yj=-1;g.h.Hy=-1;g.h.df=-1;g.h.dj=0;g.h.Ui=0;g.h.Rh=8;var B7=new g.zf;g.A(Rya,g.Ye);g.A(Sya,g.Ye);g.A(Tya,g.Ye);g.h=u7.prototype;g.h.connect=function(a,b,c,d,e){j7(0);this.Uq=b;this.Ck=c||{};d&&g.u(e)&&(this.Ck.OSID=d,this.Ck.OAID=e);this.C?(o7((0,g.z)(this.xw,this,a),100),Xya(this)):this.xw(a)};
g.h.xw=function(a){this.Yg=new Oya(this);this.Yg.Vq=null;this.Yg.l=this.B;this.Yg.connect(a)};
g.h.Gx=function(){return 0==this.g};
g.h.vB=function(a){this.ah=null;$ya(this,a)};
g.h.uB=function(){this.rg=null;this.oc=new f7(this,this.o,"rpc",this.D);this.oc.fi=null;this.oc.Yq=0;var a=this.Wv.clone();g.Bm(a,"RID","rpc");g.Bm(a,"SID",this.o);g.Bm(a,"CI",this.pp?"0":"1");g.Bm(a,"AID",this.yj);v7(this,a);if(!g.td||g.rc(10))g.Bm(a,"TYPE","xmlhttp"),g7(this.oc,a,!0,this.In,!1);else{g.Bm(a,"TYPE","html");var b=this.oc,c=!!this.In;b.lj=3;b.jh=I6(a.clone());Kya(b,c)}};
g.h.qB=function(a,b){if(0!=this.g&&(this.oc==a||this.Nd==a))if(this.df=a.Qk,this.Nd==a&&3==this.g)if(7<this.Rh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.rg){if(this.oc)if(this.oc.Pj+3E3<this.Nd.Pj)x7(this),this.oc.cancel(),this.oc=null;else break a;z7(this);j7(19)}}else this.Hy=c[1],0<this.Hy-this.yj&&37500>c[2]&&this.pp&&0==this.Ui&&!this.Th&&(this.Th=o7((0,g.z)(this.nO,this),6E3));else A7(this,11)}else b!=vAa.gX.g&&A7(this,11);else if(this.oc==a&&
x7(this),!g.D(b)){c=this.B.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.yj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.In=e[2],e=e[3],null!=e?this.Rh=e:this.Rh=6,this.g=3,this.nd&&this.nd.jw(),this.Wv=r7(this,this.Jl()?this.In:null,this.Uq),aza(this)):"stop"==e[0]&&A7(this,7):3==this.g&&("stop"==e[0]?A7(this,7):"noop"!=e[0]&&this.nd&&this.nd.iw(e),this.Ui=0)}}};
g.h.nO=function(){null!=this.Th&&(this.Th=null,this.oc.cancel(),this.oc=null,z7(this),j7(20))};
g.h.xo=function(a){if(this.oc==a){x7(this);this.oc=null;var b=2}else if(this.Nd==a)this.Nd=null,b=1;else return;this.df=a.Qk;if(0!=this.g)if(a.uf)1==b?(b=(0,g.F)()-a.Pj,B7.dispatchEvent(new Sya(B7,a.Fi?a.Fi.length:0,b,this.dj)),w7(this),this.A.length=0):aza(this);else{var c=a.kh,d;if(!(d=3==c||7==c||0==c&&0<this.df)){if(d=1==b)this.Nd||this.ah||1==this.g||2<=this.dj?d=!1:(this.ah=o7((0,g.z)(this.vB,this,a),bza(this,this.dj)),this.dj++,d=!0);d=!(d||2==b&&z7(this))}if(d)switch(c){case 1:A7(this,5);
break;case 4:A7(this,10);break;case 3:A7(this,6);break;case 7:A7(this,12);break;default:A7(this,2)}}};
g.h.uH=function(a){if(!g.Pa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.HT=function(a){a?j7(2):(j7(1),cza(this,8))};
g.h.tq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.hx;a.F=!1;return a};
g.h.isActive=function(){return!!this.nd&&this.nd.isActive(this)};
g.h.qf=function(a){B7.dispatchEvent(new Tya(B7,a))};
g.h.Jl=function(){return!(!g.td||g.rc(10))};
g.h=dza.prototype;g.h.jw=function(){};
g.h.iw=function(){};
g.h.hw=function(){};
g.h.hq=function(){};
g.h.kx=function(){return{}};
g.h.isActive=function(){return!0};g.A(D7,g.M);D7.prototype.o=function(){500<this.sc&&24E4>2*this.sc&&(this.sc*=2);this.A();this.l&&this.start()};
D7.prototype.start=function(){g.Wt(this.g,this.sc);this.l=(0,g.F)()+this.sc};
D7.prototype.stop=function(){this.g.stop();this.l=0};
D7.prototype.isActive=function(){return this.g.isActive()};g.A(E7,dza);g.h=E7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Hd=function(a){return this.o.Hd(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.We(this.o),gza(this),g.We(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new u7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.g;e&&(e.nd=null);d.nd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.yj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):F7(this)&&Yya(this.g,c)};
g.h.jw=function(){C7(this.l);this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)Yya(this.g,a[b])}this.R("handlerOpened")};
g.h.hw=function(a){var b=2==a&&401==this.g.df;if(4!=a&&!b){if(6==a||410==this.g.df)b=this.l,b.g.stop(),b.sc=500;this.l.start()}this.R("handlerError",a)};
g.h.hq=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.kx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ec(a,this.B);return a};
g.h.iw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(C7(this.l),this.l.start(),Wya(this.g)):this.R("handlerMessage",new eza(a[0],a[1]))};
g.h.sU=function(){this.l.isActive();var a=this.g,b=0;a.oc&&b++;a.Nd&&b++;0!=b?this.l.start():this.connect(this.B,this.A)};G7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
G7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
G7.prototype.B=function(a){a(Error("request timed out"))};var oza=(0,g.F)(),J7=null,M7=Array(50),L7=-1,N7=!1;g.A(O7,g.uF);O7.prototype.he=function(){return this.g};
O7.prototype.contains=function(a){return!!Q6(this.g,a)};
O7.prototype.get=function(a){return a?R6(this.g,a):null};
O7.prototype.info=function(a){K7(this.D,a)};g.A(P7,g.uF);var wAa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=P7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.za)&&this.xD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.za)||(g.ND(this.za),this.za=window.NaN)};
g.h.U=function(){this.stop();P7.Z.U.call(this)};
g.h.xD=function(){this.za=window.NaN;this.g=g.aE(H7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:this.B},timeout:5E3,Jb:(0,g.z)(this.uU,this),onError:(0,g.z)(this.tU,this),rd:(0,g.z)(this.vU,this)})};
g.h.uU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new L6(c))};
g.h.tU=function(a){this.g=null;a.status&&404==a.status?this.l>=wAa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=wAa[this.l],this.za=g.LD((0,g.z)(this.xD,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.vU=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(R7,O7);g.h=R7.prototype;g.h.start=function(){Q7(this)&&this.R("screenChange");!g.uG("yt-remote-lounge-token-expiration")&&sza(this);g.ND(this.l);this.l=g.LD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){Q7(this);pza(this,a);S7(this,!1);this.R("screenChange");b(a);a.token||sza(this)};
g.h.remove=function(a,b){var c=Q7(this);rza(this,a)&&(S7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.kp=function(a,b,c,d){var e=Q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,S7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.U=function(){g.ND(this.l);R7.Z.U.call(this)};
g.h.ZH=function(a){Q7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}S7(this,!b);b&&K7(this.D,"Missed "+b+" lounge tokens.")};
g.h.YH=function(a){K7(this.D,"Requesting lounge tokens failed: "+a)};g.A(U7,g.uF);g.h=U7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.uG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?W7(this):(this.A=(0,g.F)()+3E5,g.tG("yt-remote-fast-check-period",this.A),this.Qt())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){T7("Updating availability on schedule.");var a=this.C(),b=g.Mb(this.g,function(b,d){return b&&!!R6(a,d)},this);
V7(this,b)};
g.h.U=function(){g.ND(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);U7.Z.U.call(this)};
g.h.Qt=function(){g.ND(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=vza(this);if(g.Pb(a)){var b=H7(this.B,"/pairing/get_screen_availability");this.l=I7(this.B,b,{lounge_token:g.Rb(a).join(",")},(0,g.z)(this.pR,this,a),(0,g.z)(this.oR,this))}else V7(this,{}),W7(this)};
g.h.pR=function(a,b){this.l=null;var c=g.Rb(vza(this));if(g.ib(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;V7(this,d);W7(this)}else this.ac("Changing Screen set during request."),this.Qt()};
g.h.oR=function(a){this.ac("Screen availability failed: "+a);this.l=null;W7(this)};
g.h.ac=function(a){K7("OnlineScreenService",a)};g.A(X7,O7);g.h=X7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.kp=function(a,b,c,d){this.o.contains(a)?this.o.kp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,K7(this.D,a),d(Error(a)))};
g.h.he=function(a){return a?this.g:g.Wa(this.g,(0,g.Hd)(this.A,function(a){return!this.contains(a)},this))};
g.h.yD=function(){return(0,g.Hd)(this.he(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.zD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new P7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.We(f);d(Y7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.We(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.xU=function(a,b,c,d){g.aE(H7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:a},timeout:5E3,Jb:(0,g.z)(function(a,d){var e=new L6(d.screen||{});if(!e.name||zza(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);zza(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(Y7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
rd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.We(this.o);g.We(this.l);X7.Z.U.call(this)};
g.h.pI=function(){Aza(this);this.R("screenChange");this.l.update()};
X7.prototype.dispose=X7.prototype.dispose;g.A($7,g.uF);g.h=$7.prototype;g.h.yo=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.ne=function(a){this.ha()||(a&&a8(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){K7(this.L,a)};
g.h.BD=function(){return null};
g.h.Yt=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){a8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Yt("");$7.Z.U.call(this)};g.A(b8,$7);g.h=b8.prototype;g.h.Xt=function(a){if(this.g){if(this.g==a)return;a8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Cza(this)};
g.h.zj=function(a){this.info("launchWithParams no-op for Cast: "+g.ug(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.ne()},this),(0,g.z)(function(){this.ne(Error("Failed to stop receiver app."))},this)):this.ne(Error("Stopping cast device witout session."))};
g.h.Yt=g.y;g.h.U=function(){this.info("disposeInternal");g.ND(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;b8.Z.U.call(this)};
g.h.qS=function(a,b){if(!this.ha())if(b){var c=g.bx(b);if(c){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.ug(c));switch(d){case "mdxSessionStatus":Bza(this,c.screenId);break;default:a8(this,"Unknown youtube message: "+d)}}else a8(this,"Unable to parse message.")}else a8(this,"No data in message.")};
g.h.zx=function(a,b,c,d){yza(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(a8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.LD((0,g.z)(this.zx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.BD=function(){return this.g};
g.h.yU=function(a){this.ha()||a||(a8(this,"Cast session died."),this.ne())};g.A(c8,$7);g.h=c8.prototype;g.h.Xt=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.zj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.ND(this.C);this.A?this.A.stop((0,g.z)(this.ne,this,null),(0,g.z)(this.ne,this,"Failed to stop DIAL device.")):this.ne()};
g.h.U=function(){this.g();this.g=g.y;g.ND(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;c8.Z.U.call(this)};
g.h.BU=function(a){this.ha()||a||(a8(this,"DIAL session died."),this.g(),this.g=g.y,this.ne())};
g.h.Kr=function(a){this.I=P6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,Eza(this));a(b);Dza(this)}else this.D=(0,g.z)(function(){g.ND(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,Eza(this));a(b);Dza(this)},this),this.C=g.LD((0,g.z)(function(){this.D()},this),100)};
g.h.GJ=function(a,b,c){yza(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.yo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Kr(b,c)},this),(0,g.z)(function(a){a8(this,"Failed to get DIAL screen: "+a);
this.Kr(b,c)},this))};g.A(d8,$7);d8.prototype.stop=function(){this.ne()};
d8.prototype.Xt=g.y;d8.prototype.zj=function(){g.ND(this.g);this.g=window.NaN;var a=R6(this.H.he(),this.l.label);a?this.yo(a):this.ne(Error("No such screen"))};
d8.prototype.U=function(){g.ND(this.g);this.g=window.NaN;d8.Z.U.call(this)};g.A(e8,g.uF);g.h=e8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.rB,this),(0,g.z)(this.aR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.YO,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),lza(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.AD,this)),this.o=Gza(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.ug(a))},this)),this.R("yt-remote-cast2-availability-change",g8(this)),b(!0))},this),(0,g.z)(function(a){this.ac("Failed to initialize API: "+g.ug(a));
b(!1)},this))};
g.h.qT=function(a,b){f8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)f8("Unsetting old screen status: "+this.g.l.friendlyName),h8(this,null)}if(a&&b){if(!this.g){c=R6(this.l.he(),a);if(!c){f8("setConnectedScreenStatus: Unknown screen.");return}var d=Fza(this,c);d||(f8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.ac("Failed to set initial custom receivers: "+g.ug(a))},this)));
f8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);h8(this,new d8(this.l,d),!0)}this.g.Yt(b)}else f8("setConnectedScreenStatus: no screen.")};
g.h.rT=function(a){this.ha()?this.ac("Setting connection data on disposed cast v2"):this.g?this.g.zj(a):this.ac("Setting connection data without a session")};
g.h.AU=function(){this.ha()?this.ac("Stopping session on disposed cast v2"):this.g?(this.g.stop(),h8(this,null)):f8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.rB,this),(0,g.z)(this.tR,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.AD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],iza);g.We(this.g);e8.Z.U.call(this)};
g.h.ac=function(a){K7("Controller",a)};
g.h.sB=function(a,b){this.g==a&&(b||h8(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.WQ=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),f8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)f8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{f8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:h8(this,
new d8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:h8(this,new c8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:h8(this,new b8(this.l,a));break;default:this.ac("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.ac("Stopping receiver w/o session: "+a.friendlyName)}else this.ac("onReceiverAction_ called without receiver.")};
g.h.YO=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.ac("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.ac("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return f8("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.ac('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);h8(this,new c8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.GJ,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Kr,b))};
g.h.rB=function(a){if(!this.ha()){f8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)f8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),h8(this,new b8(this.l,b),!0);else{this.ac("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=R6(this.l.he(),c.label);
d&&M6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(f8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.We(this.g),this.g=new b8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.sB,this,this.g)),this.g.zj(null));this.g.Xt(a)}}};
g.h.zU=function(){return this.g?this.g.BD():null};
g.h.tR=function(a){this.ha()||(this.ac("Failed to estabilish a session: "+g.ug(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&h8(this,null))};
g.h.aR=function(a){f8("Receiver availability updated: "+a);if(!this.ha()){var b=g8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;g8(this)!=b&&this.R("yt-remote-cast2-availability-change",g8(this))}};
g.h.AD=function(){this.ha()||(this.o=Gza(this),f8("Updating custom receivers: "+g.ug(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.ac("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",g8(this)))};
e8.prototype.setLaunchParams=e8.prototype.rT;e8.prototype.setConnectedScreenStatus=e8.prototype.qT;e8.prototype.stopSession=e8.prototype.AU;e8.prototype.getCastSession=e8.prototype.zU;e8.prototype.requestSession=e8.prototype.requestSession;e8.prototype.init=e8.prototype.init;e8.prototype.dispose=e8.prototype.dispose;var n8=[];s8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";t8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Jf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
s8.prototype.jb=function(){return 1==this.g};
s8.prototype.getDuration=function(){return this.C?this.H+u8(this):this.H};
s8.prototype.clone=function(){return new s8(y8(this))};g.A(A8,g.uF);g.h=A8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,G8(this,"play")):F8(this,"play"),E8(this,1,w8(B8(this))),this.R("remotePlayerChange")):C8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,G8(this,"pause")):F8(this,"pause"),E8(this,2,w8(B8(this))),this.R("remotePlayerChange")):C8(this,this.pause)};
g.h.wD=function(a){if(1==this.g){if(this.l){var b=B8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,G8(this,"seekTo",{newTime:a}))}else F8(this,"seekTo",{newTime:a});E8(this,3,a);this.R("remotePlayerChange")}else C8(this,g.Da(this.wD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,G8(this,"stopVideo")):F8(this,"stopVideo");var a=B8(this);a.index=-1;a.videoId="";t8(a);D8(this,a);this.R("remotePlayerChange")}else C8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=B8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){K7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){K7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);F8(this,"setVolume",e)}c.muted=b;c.volume=a;D8(this,c)}else C8(this,g.Da(this.setVolume,a,b))};
g.h.xC=function(a,b){if(1==this.g){var c=B8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.ug(b.style),g.ec(d,c.l));F8(this,"setSubtitlesTrack",d);D8(this,c)}else C8(this,g.Da(this.xC,a,b))};
g.h.Mu=function(a,b){if(1==this.g){F8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Oc.id});var c=B8(this);c.audioTrackId=b.Oc.id;D8(this,c)}else C8(this,g.Da(this.Mu,a,b))};
g.h.vD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"previous")}else C8(this,g.Da(this.vD,a,b))};
g.h.uD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"next")}else C8(this,g.Da(this.uD,a,b))};
g.h.Mw=function(){1==this.g?F8(this,"dismissAutoplay"):C8(this,this.Mw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}A8.Z.dispose.call(this)};
g.h.U=function(){Tza(this);this.A=null;this.B.clear();z8(this,null);A8.Z.U.call(this)};
g.h.Nu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.jC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.SQ=function(a,b){this.R(a,b)};
g.h.uO=function(a){if(!a)this.zl(null),z8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=B8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)K7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,D8(this,b)}};
g.h.zl=function(a){K7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),Uza(this),this.R("remotePlayerChange")};
g.h.tO=function(a){a?(Uza(this),this.R("remotePlayerChange")):this.zl(null)};
g.h.HO=function(){var a=Qza();a&&z8(this,a)};
g.h.ac=function(a){K7("CP",a)};g.A(H8,g.uF);g.h=H8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.fb.listId=c);this.fb.videoId=d;this.fb.index=k||0;this.fb.state=3;v8(this.fb,m);this.A="UNSUPPORTED";I8("Connecting with setPlaylist and params: "+g.ug(l));this.g.connect({method:"setPlaylist",params:g.ug(l)},a,pya())}else I8("Connecting without params"),
this.g.connect({},a,pya());Wza(this)};
g.h.dispose=function(){this.ha()||(this.R("beforeDispose"),J8(this,3));H8.Z.dispose.call(this)};
g.h.U=function(){K8(this);M8(this);L8(this);g.ND(this.H);this.H=window.NaN;g.ND(this.I);this.I=window.NaN;this.o=null;g.fF(this.V);this.V.length=0;this.g.dispose();H8.Z.U.call(this);this.A=this.D=this.l=this.fb=this.g=null};
g.h.QH=function(){this.C(2)};
g.h.yO=function(){I8("Channel opened");this.N&&(this.N=!1,L8(this),this.L=g.LD((0,g.z)(function(){I8("Timing out waiting for a screen.");this.C(1)},this),15E3));
tya(fza(this.g),this.X)};
g.h.vO=function(){I8("Channel closed");(0,window.isNaN)(this.B)?W6(!0):W6();this.dispose()};
g.h.wO=function(a){W6();(0,window.isNaN)(this.F())?(I8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,I8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),J8(this,2))};
g.h.xO=function(a){a.params?I8("Received: action="+a.action+", params="+g.ug(a.params)):I8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.bx(a.params.devices);this.l=(0,g.H)(a,function(a){return new K6(a)});
a=!!g.Ja(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Zza(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Zza(this,!1);break;case "remoteConnected":var b=new K6(g.bx(a.params.device));g.Ja(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new K6(g.bx(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":aAa(this,a);break;case "nowPlaying":cAa(this,a);break;case "onStateChange":bAa(this,a);break;case "onAdStateChange":dAa(this,a);break;case "onVolumeChanged":eAa(this,a);break;case "onSubtitlesTrackChanged":$za(this,a);break;case "nowAutoplaying":fAa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":gAa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:I8("Unrecognized action: "+a.action)}};
g.h.aT=function(){if(this.o){var a=this.o;this.o=null;this.fb.videoId!=a&&N8(this,"getNowPlaying")}};
H8.prototype.subscribe=H8.prototype.subscribe;H8.prototype.unsubscribeByKey=H8.prototype.Hd;H8.prototype.da=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?F7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
H8.prototype.getProxyState=H8.prototype.da;H8.prototype.C=function(a){I8("Disconnecting with "+a);K8(this);this.R("beforeDisconnect",a);1==a&&W6();gza(this.g,a);this.dispose()};
H8.prototype.disconnect=H8.prototype.C;H8.prototype.ca=function(){var a=this.fb;this.o&&(a=this.fb.clone(),x8(a,this.o,a.index));return y8(a)};
H8.prototype.getPlayerContextData=H8.prototype.ca;
H8.prototype.ka=function(a){var b=new s8(a);b.videoId&&b.videoId!=this.fb.videoId&&(this.o=b.videoId,g.ND(this.H),this.H=g.LD((0,g.z)(this.aT,this),5E3));var c=[];this.fb.listId==b.listId&&this.fb.videoId==b.videoId&&this.fb.index==b.index||c.push("remoteQueueChange");this.fb.g==b.g&&this.fb.volume==b.volume&&this.fb.muted==b.muted&&w8(this.fb)==w8(b)&&g.ug(this.fb.l)==g.ug(b.l)||c.push("remotePlayerChange");this.fb.reset(a);(0,g.C)(c,function(a){this.R(a)},this)};
H8.prototype.setPlayerContextData=H8.prototype.ka;H8.prototype.W=function(){var a=this.g.C.id,b=g.Ja(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
H8.prototype.getOtherConnectedRemoteId=H8.prototype.W;H8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
H8.prototype.getReconnectTimeout=H8.prototype.F;H8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
H8.prototype.getAutoplayMode=H8.prototype.Y;H8.prototype.ba=function(){return this.D||""};
H8.prototype.getAutoplayVideoId=H8.prototype.ba;H8.prototype.ma=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Xt(a.g);a.start()}};
H8.prototype.reconnect=H8.prototype.ma;H8.prototype.fa=function(a,b){N8(this,a,b);Yza(this)};
H8.prototype.sendMessage=H8.prototype.fa;g.A(O8,O7);g.h=O8.prototype;g.h.he=function(a){return this.bd.$_gs(a)};
g.h.contains=function(a){return!!this.bd.$_c(a)};
g.h.get=function(a){return this.bd.$_g(a)};
g.h.start=function(){this.bd.$_st()};
g.h.add=function(a,b,c){this.bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.bd.$_r(a,b,c)};
g.h.kp=function(a,b,c,d){this.bd.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.bd.$_ubk(this.l[a]);this.l.length=0;this.bd=null;O8.Z.U.call(this)};
g.h.wU=function(){this.R("screenChange")};
g.h.tQ=function(){this.R("onlineScreenChange")};
X7.prototype.$_st=X7.prototype.start;X7.prototype.$_gspc=X7.prototype.xU;X7.prototype.$_gsppc=X7.prototype.zD;X7.prototype.$_c=X7.prototype.contains;X7.prototype.$_g=X7.prototype.get;X7.prototype.$_a=X7.prototype.add;X7.prototype.$_un=X7.prototype.kp;X7.prototype.$_r=X7.prototype.remove;X7.prototype.$_gs=X7.prototype.he;X7.prototype.$_gos=X7.prototype.yD;X7.prototype.$_s=X7.prototype.subscribe;X7.prototype.$_ubk=X7.prototype.Hd;var P8=null,Q8=null,e9=null,U8=[];g.p(f9,g.M);g.h=f9.prototype;
g.h.U=function(){g.M.prototype.U.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.pB,this);this.g.unsubscribe("remotePlayerChange",this.Bl,this);this.g.unsubscribe("remoteQueueChange",this.zo,this);this.g.unsubscribe("autoplayUpNext",this.LA,this);this.g.unsubscribe("previousNextChange",this.mB,this);this.g.unsubscribe("nowAutoplaying",this.eB,this);this.g.unsubscribe("autoplayDismissed",this.KA,this);this.g=this.F=null};
g.h.wz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(i9(this)){if(1081!=B8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":B8(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.jj(c[0],c[1]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Mu(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();k9(this,0==c?void 0:c);break;case "control_seek":k9(this,c[0]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Mu(this.l.ea(1).videoId,c)}};
g.h.sO=function(a){this.K.MH(a)};
g.h.UT=function(a){this.wz("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.KC=function(){var a=this.l.xc("captions","track");g.Xb(a)||j9(this,a)};
g.h.cB=function(a){if(i9(this)){this.g.unsubscribe("remotePlayerChange",this.Bl,this);var b=Math.round(a.volume);a=!!a.muted;var c=B8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.Bl,this)}};
g.h.MP=function(){g.Xb(this.C)||sAa(this,this.C);this.D=!1};
g.h.pB=function(a,b){this.B.stop();2==b&&this.HC()};
g.h.Bl=function(){if(i9(this)){this.A.stop();var a=B8(this.g);switch(a.g){case 1081:case 1:h9(this,new g.nO(8));this.GC();break;case 1085:case 3:h9(this,new g.nO(9));break;case 1083:case 0:h9(this,new g.nO(2));this.I.stop();g9(this,this.l.ea().lengthSeconds);break;case 1084:h9(this,new g.nO(4));break;case 2:h9(this,new g.nO(4));g9(this,w8(a));break;case -1:h9(this,new g.nO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},h9(this,new g.nO(128,a))}a=B8(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,sAa(this,a));a=B8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.L.isActive()||this.nD()}else rAa(this)};
g.h.mB=function(){this.l.R("mdxpreviousnextchange")};
g.h.zo=function(){i9(this)||rAa(this)};
g.h.XG=function(){this.g.Mw()};
g.h.LA=function(a){a&&(a=g.aE("/watch_queue_ajax",{method:"GET",Wc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.z)(this.SR,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.SR=function(a,b){var c=new g.oN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.eB=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.KA=function(){this.l.R("mdxautoplaycanceled")};
g.h.mL=function(a,b){-1==B8(this.g).g?k9(this,a):b&&this.g.wD(a)};
g.h.nD=function(){if(i9(this)){var a=B8(this.g);this.o.Da(this.V);a.muted?this.l.mute():this.l.Xf();this.l.setVolume(a.volume);this.V=this.o.O(this.l,"onVolumeChange",this.cB)}};
g.h.GC=function(){this.A.stop();if(!this.g.ha()){var a=B8(this.g);a.jb()&&h9(this,new g.nO(8));g9(this,w8(a));this.A.start()}};
g.h.HC=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(l9,g.Y);l9.prototype.A=function(a){uAa(this,a.state)};g.p(m9,g.M_);m9.prototype.I=function(){var a=this.l.xc("remote","receivers");a&&1<a.length&&!this.l.xc("remote","quickCast")?(this.F=g.kb(a,this.B,this),g.N_(this,(0,g.H)(a,this.B)),a=this.l.xc("remote","currentReceiver"),this.pf(this.B(a)),this.enable(!0)):this.enable(!1)};
m9.prototype.B=function(a){return a.key};
m9.prototype.nf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
m9.prototype.qd=function(a){g.M_.prototype.qd.call(this,a);this.l.Fd("remote","currentReceiver",this.F[a]);this.A.Ob()};g.p(n9,g.DU);g.h=n9.prototype;g.h.create=function(){lAa(g.LL(g.W(this.g)));this.C.push(g.GF("yt-remote-before-disconnect",this.oO,this));this.C.push(g.GF("yt-remote-connection-change",this.bR,this));this.C.push(g.GF("yt-remote-receiver-availability-change",this.nB,this));this.C.push(g.GF("yt-remote-auto-connect",this.ZQ,this));this.C.push(g.GF("yt-remote-receiver-resumed",this.YQ,this));this.nB()};
g.h.load=function(){this.g.Ns();g.DU.prototype.load.call(this);this.B=new f9(this,this.g,this.l);var a=(a=qAa())?a.currentTime:0;var b=d9()?new A8(Z8(),void 0):null;0==a&&b&&(a=w8(B8(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));tAa(this,this.D,this.D);g.E0(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.Xe(this.B,this.l);this.l=this.B=null;g.DU.prototype.unload.call(this);g.E0(this.g.app,5)};
g.h.U=function(){g.HF(this.C);g.DU.prototype.U.call(this)};
g.h.jl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.wz.apply(this.B,[].concat([a],g.pa(c)))};
g.h.IH=function(){return this.loaded?this.B.suggestion:null};
g.h.Jf=function(){return this.l?B8(this.l).Jf:!1};
g.h.hasNext=function(){return this.l?B8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.NK=function(){var a=B8(this.l),b=this.g.ea();return{allowSeeking:this.g.cd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+u8(a):a.A,isPeggedToLive:1>=(a.C?a.o+u8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+u8(a):a.o,seekableStart:0<a.B?a.B+u8(a):a.B}};
g.h.OK=function(){this.l&&this.l.uD()};
g.h.PK=function(){this.l&&this.l.vD()};
g.h.oO=function(a){1==a&&(this.I=this.l?B8(this.l):null)};
g.h.bR=function(){var a=d9()?new A8(Z8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.We(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.Gz(a.videoId,w8(a)));this.g.R("videodatachange","newdata",this.g.ea(),3)};
g.h.nB=function(){this.F=[this.o].concat(nAa());var a=$8()||this.o;o9(this,a);this.g.ra("onMdxReceiversChange")};
g.h.ZQ=function(){var a=$8();o9(this,a)};
g.h.YQ=function(){this.A=$8()};
g.h.MK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?q8():o9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&q8(),!0):!1}};
g.h.QK=function(){F8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.td=function(){return!1};g.LY.remote=n9;})(_yt_player);
